//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class student
    {
        public int sid { get; set; }
        public string sname { get; set; }
        public string saddress { get; set; }
        public Nullable<long> contacts { get; set; }
    }
}
